# Permalinks
permalink: /:title/github-pages
baseurl: ""
title: "向往自由的程序猿"
auth: "林跑跑"
describe: "学不可以已"
personalLabels: ["Java","AngularJs"]
paginate: 5
kramdown:
  input: GFM
gems:                [jekyll-paginate]
